version: '3.3'

services:
  live_map:
    build:
      context: .
    container_name: live_map
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    command: sh -c "python app.py"
    depends_on:
      - kafka

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - "9092:9092"
    environment:  
      - KAFKA_BROKER_ID=1         
      - KAFKA_LISTENERS=PLAINTEXT://:9092 
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
      - ALLOW_PLAINTEXT_LISTENER=yes      
    depends_on:
      - zookeeper  